services:
  - postgresql
language: ruby
rvm:
  - 2.7.0
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec
